const PRODUCT_CATEGORY_THEMES = {
  actividades: {
    primary: "#f97316",
    secondary: "#ea580c",
    accent: "#9a3412",
    soft: "#fff7ed",
    softAlt: "#ffedd5",
    border: "rgba(249, 115, 22, 0.24)",
    surface: "#fffaf5",
    surfaceStrong: "#fed7aa",
    chipBg: "#ffffff",
    chipText: "#c2410c",
    shadow: "rgba(234, 88, 12, 0.18)",
    muted: "#7c2d12",
    icon: "local_activity",
  },
  transporte: {
    primary: "#10b981",
    secondary: "#047857",
    accent: "#065f46",
    soft: "#ecfdf5",
    softAlt: "#d1fae5",
    border: "rgba(16, 185, 129, 0.22)",
    surface: "#f4fffa",
    surfaceStrong: "#a7f3d0",
    chipBg: "#ffffff",
    chipText: "#047857",
    shadow: "rgba(4, 120, 87, 0.16)",
    muted: "#065f46",
    icon: "directions_car",
  },
  restaurantes: {
    primary: "#ef4444",
    secondary: "#dc2626",
    accent: "#991b1b",
    soft: "#fef2f2",
    softAlt: "#fee2e2",
    border: "rgba(239, 68, 68, 0.24)",
    surface: "#fff7f7",
    surfaceStrong: "#fecaca",
    chipBg: "#ffffff",
    chipText: "#b91c1c",
    shadow: "rgba(220, 38, 38, 0.16)",
    muted: "#991b1b",
    icon: "restaurant",
  },
  planes: {
    primary: "#2563eb",
    secondary: "#1d4ed8",
    accent: "#1e3a8a",
    soft: "#eff6ff",
    softAlt: "#dbeafe",
    border: "rgba(37, 99, 235, 0.22)",
    surface: "#f8fbff",
    surfaceStrong: "#bfdbfe",
    chipBg: "#ffffff",
    chipText: "#1d4ed8",
    shadow: "rgba(29, 78, 216, 0.16)",
    muted: "#1e3a8a",
    icon: "map",
  },
  excursiones: {
    primary: "#0891b2",
    secondary: "#0e7490",
    accent: "#155e75",
    soft: "#ecfeff",
    softAlt: "#cffafe",
    border: "rgba(8, 145, 178, 0.22)",
    surface: "#f4fdff",
    surfaceStrong: "#a5f3fc",
    chipBg: "#ffffff",
    chipText: "#0e7490",
    shadow: "rgba(14, 116, 144, 0.16)",
    muted: "#155e75",
    icon: "explore",
  },
};

export function getProductCategoryTheme(categoryId = "actividades") {
  return PRODUCT_CATEGORY_THEMES[categoryId] ?? PRODUCT_CATEGORY_THEMES.actividades;
}

export function getProductCategoryCssVars(categoryId = "actividades") {
  const theme = getProductCategoryTheme(categoryId);

  return {
    "--product-theme-primary": theme.primary,
    "--product-theme-secondary": theme.secondary,
    "--product-theme-accent": theme.accent,
    "--product-theme-soft": theme.soft,
    "--product-theme-soft-alt": theme.softAlt,
    "--product-theme-border": theme.border,
    "--product-theme-surface": theme.surface,
    "--product-theme-surface-strong": theme.surfaceStrong,
    "--product-theme-chip-bg": theme.chipBg,
    "--product-theme-chip-text": theme.chipText,
    "--product-theme-shadow": theme.shadow,
    "--product-theme-muted": theme.muted,
  };
}
